### ISSUE TITLE
Cara akses string resources di mvp

### ISSUE THREAD

**Issue by qornanali** [isfaaghyth/MVP#1]
Implementasi dulu contohnya seperti ini
`mContext.getString(R.String.text_login);`

Cara apa yang best practices untuk mengakses string resources di arsitektur mvp android?
Apakah dengan mengirimkan context melalui parameter constructornya presenter?

**Comment by isfaaghyth** [comment]
best practices nya bisa pakai dependecy injection li seperti dagger.
atau bisa kmu passing context() nya melalui view.
atau ada satu cara lagi, bisa di declare di Application tapi ngga direkomendasikan.

**Comment by qornanali** [comment]
contohnya kayak gini ?

MainView.java
```
public interface MainView extends BaseView<List<BlogPost>>{

 Context getContext();

}
```
MainActivity.java
```
public class MainActivity extends MvpActivity<MainPresenter> implements MainView{

@Override
public void Context getContext(){
return this;
}
}
```

**Comment by isfaaghyth** [comment]
yap, bisa seperti itu :)
